### ISSUE TITLE
Launching the game with the GUI too

### ISSUE THREAD

**Issue by mddanish00** [tynave/PriconneReTL-Installer#4]
Before this, I used [PriconeTL_Updater](https://github.com/touanu/PriconeTL_Updater) as a shortcut to automatically update the patch (if available) and launch the game. By using it like this, I don't need to manually check for updates and will automatically on the latest patch when launching the game.

So, I wonder if you have any plans to add launching the game functionality to the GUI? Maybe only the program detects [DMMGamePlayerFastLauncher](https://github.com/fa0311/DMMGamePlayerFastLauncher).

**Comment by tynave** [comment]
Hi there! 
Thank you for the feedback!

The BepInEx framework we use for the translation patch has the ability to handle so called "pre-load patchers" which can be applied/run before the actual patch is loaded.
I am currently working a autoupdater that utilizes this, meaning that every time you start the game, a pre-load patcher launches a stripped-down version of my GUI which checks for / performs the update automatically before starting the game itself.
The only minor drawback of it is that the patch framework files themselves cannot be updated like this, but those rarely ever change, and if they do, then a manual install can update those as well.

Nevertheless, I should be able to add a game launch functionality into the GUI as well. 
I was actually planning to do it in the first place, but it wasn't high on my priority list and somehow got forgotten. 
I didn't figure it is used by many, sorry :)

As the GUI itself operates manually - I mean you have to push the button for something to happen - how about I add another button that launches the game?
Or maybe a selectable option (checkbox) to have the game launched after an update/install/reinstall, although that would also require to press the Start button, even if you can see that there is no new version.
Let me know if you have ideas.
In the end, I think in the GUI, it would still be somewhat manual, the closest to what you would like will be the autoupdater :)

**Comment by Miracutor** [comment]
My idea like this. Maybe add two more checkboxes, Update and Launch. 
If an update is available, the Update option will automatically selected but the user still can pick Launch option if desired. 
After updating complete or if no update, Launch will be automatically selected but Update option will be disabled.

**Comment by Miracutor** [comment]
> You mean keep one button, and change the functionality / behavior depending on which checkbox(es) is/are selected?

Yes

> So in this case, both should be selectable?

No. My intention is that the user can skip from updating if the user want to launch the game without updating the patch.

You also can add function like automatically launch the game after installing/updating/reinstalling if you want by placing a checkbox 'Launch when finished' below that Start button.

**Comment by tynave** [comment]
How's this:
2 new checkboxes: one for the operation (update/install/uninstall/reinstall - changes depending on what is performed), and one for launching the game.
If you only select the one for the operation, it only manipulates the patch.
If you only select launch, it only launches the game.
If you select both, it does both.
And of course handling the exceptions, like you can't update if there is no new version, and so on.
I think i can make the checkbox states persist as well. (If you check the box, it'll be checked on next app launch as well)

Or another idea:
Two new checkboxes, one lets you just launch the game without any install/update whatsoever, and the other makes the game launch upon completing the install/update.
You can select only either, or none, if you don't want to launch the game.

I like the first one better tho.

(btw, I need to look into it a bit more, but I think I'm able to have the original DMM launcher to be started if the user does not have DMMGamePlayerFastLauncher)

**Comment by Miracutor** [comment]
I also think the first one is better too. The second one feels redundant.

> (btw, I need to look into it a bit more, but I think I'm able to have the original DMM launcher to be started if the user does not have DMMGamePlayerFastLauncher)

This is good.

**Comment by tynave** [comment]
Added the launcher capability into the new release.
https://github.com/tynave/PriconneReTL-Installer/releases/tag/1.2.0
