### ISSUE TITLE
Launching the game using the App not working

### ISSUE THREAD

**Issue by mddanish00** [tynave/PriconneReTL-Installer#5]
I tried to launch the game using the app but nothing even the game did not appear at all in Task Manager. I tried to launch it 5 times, but it never succeeded once.

At first, I thought maybe it needed the latest version of [DMMGamePlayerFastLauncher](https://github.com/fa0311/DMMGamePlayerFastLauncher). Previously, I was on the v4.9 version. But it is just the same. So, that is not the problem. I reverted back to the v4.9 version because the newer one feels complicated and the old one more stable.

Then, I remembered that [PriconeTL_Updater](https://github.com/touanu/PriconeTL_Updater) always asked for administrator privilege, so maybe for that reason. So, I tried to launch the app and run it as Administrator. And... it works!

So, maybe you need to add that?

**Comment by tynave** [comment]
Hm.. Interesting. 
I had several people test it out including myself and none of them reported the need of admin mode.

What I can do it to add a comment to the readme, that if the launch does not work, then run the installer in admin mode.
I wouldn't want to make the app require admin mode in the first place, as that might scare off users or give them the wrong impression of the app trying to do somethin fishy on their PC. :D

**Comment by mddanish00** [comment]
> I wouldn't want to make the app require admin mode in the first place, as that might scare off users or give them the wrong impression of the app trying to do somethin fishy on their PC. :D

Yeah... That's make sense. 😅

Weird... It kind of inconsistent. For me, yes, sometimes it works but really rare.

I think maybe DMMGamePlayerFastLauncher is the one that inconsistent? I remember make shortcut with command to DMMGamePlayerFastLauncher to launch Priconne before and has the same experience. So, administrator privilege make it consistently work maybe?🤔

**Comment by tynave** [comment]
I released version 1.4.0 of the installer, which uses a new approach for launching via DMMGamePlayerFastLauncher.
You have to set the shortcut created by the fastlauncher for the game in the installer, and then it will launch the game via that shortcut. This way it will be compatible with both the older 4.x and the currect 5.x versions.
