### ISSUE TITLE
Auto Updater isn't working

### ISSUE THREAD

**Issue by Uryaaa** [tynave/PriconneReTL-Installer#6]
logs
```
[PriconneReTL AutoUpdaterApp version: 1.0.0.0]
[Log file created at: 11/3/2023 9:50:53 PM]
[11/3/2023 9:50:54 PM] - Found new version! Starting update...
[11/3/2023 9:50:58 PM] - Downloading compressed patch files...
[11/3/2023 9:50:58 PM] - ERROR: Error downloading patch files: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
[11/3/2023 9:50:58 PM] - ERROR: Update failed!
```

**Comment by Uryaaa** [comment]
[LogOutput.log](https://github.com/tynave/PriconneReTL-Installer/files/13262362/LogOutput.log) (i'm not sure if this file got replaced with new one, because i just update it manually using [PriconneReTL-Installer 1.3.0](https://github.com/tynave/PriconneReTL-Installer/releases/tag/1.3.0))

i'm trying to update from [Pricone UI EN DMM v20231024](https://github.com/ImaterialC/PriconneRe-TL/releases/tag/20231024) to the latest version

**Comment by tynave** [comment]
Thanks.
Yeah this file gets replaced on every game start and as you don't have the autoupdater anymore, this doesn't have what I was looking for anymore unfortunately. + updated to the latest version, so reproducing the error would require some manual modification of the tl patch. (I can tell you how if you wanna try again)

I'll try to improve the logging in the aautoupdater and maybe you can try it again (worst case the next time a new tl patch version is released.)
Sorry for the inconvenience, the code of the autoupdater is based on the installer, so I wonder what could've gone wrong there.

**Comment by Uryaaa** [comment]
Maybe i can reproduce the error in PriconneTL next update.

**Comment by Uryaaa** [comment]
[LogOutput.log](https://github.com/tynave/PriconneReTL-Installer/files/13324242/LogOutput.log)
this is the new BeplnEx log when i'm trying to use auto updater
![image](https://github.com/tynave/PriconneReTL-Installer/assets/61571823/759e38d9-aeae-4895-b944-ff06ad041ecc)

**Comment by tynave** [comment]
Aaah god I have totally not considered paths that have spaces in them.
I'll fix these soon. 
Thanks!

**Comment by tynave** [comment]
I released 1.0.1 of the dll file:
https://github.com/tynave/PriconneReTL-AutoUpdater/releases/tag/1.0.1

Can you please test it and let me know? Thanks!

**Comment by Uryaaa** [comment]
It's good now, the patch installed successfully!

![image](https://github.com/tynave/PriconneReTL-Installer/assets/61571823/75ac2411-13c7-43e7-b09a-7da1b7effcb3)

**Comment by tynave** [comment]
Glad to hear!
This issue is closed then. Let me know if you run into any more trouble, hopefully not ;)
